version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app

